[options]
girs_dir = "gir-files"
library = "Gsk"
version = "4.0"
min_cfg_version = "4.0.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gsk.BlendMode",
    "Gsk.CairoRenderer",
    "Gsk.Corner",
    "Gsk.GLRenderer",
    "Gsk.GLUniformType",
    "Gsk.RenderNodeType",
    "Gsk.ScalingFilter",
    "Gsk.SerializationError",
    "Gsk.ShaderArgsBuilder",
    "Gsk.TransformCategory",
]

manual = [
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.RGBA",
    "Gdk.Surface",
    "Gdk.Texture",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Quark",
    "GLib.String",
    "Graphene.Matrix",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Rect",
    "Graphene.Size",
    "Graphene.Vec2",
    "Graphene.Vec3",
    "Graphene.Vec4",
    "Gsk.BlendNode",
    "Gsk.BlurNode",
    "Gsk.CairoNode",
    "Gsk.ClipNode",
    "Gsk.ColorMatrixNode",
    "Gsk.ColorNode",
    "Gsk.ColorStop",
    "Gsk.ContainerNode",
    "Gsk.CrossFadeNode",
    "Gsk.DebugNode",
    "Gsk.GLShaderNode",
    "Gsk.InsetShadowNode",
    "Gsk.OpacityNode",
    "Gsk.OutsetShadowNode",
    "Gsk.RepeatNode",
    "Gsk.RoundedClipNode",
    "Gsk.RoundedRect",
    "Gsk.Shadow",
    "Gsk.TextureNode",
    "Gsk.TransformNode",
    "Pango.Font",
    "Pango.GlyphInfo",
    "Pango.GlyphString",
]

[[object]]
name = "Gsk.*"
status = "generate"

[[object]]
name = "Gsk.BroadwayRenderer"
status = "generate"
cfg_condition = "feature = \"broadway\""

[[object]]
name = "Gsk.GLShader"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "format_args_va"
    ignore = true # not useful for bindings

[[object]]
name = "Gsk.Renderer"
status = "generate"
manual_traits = ["RendererExtManual"]
    [[object.function]]
    name = "render"
    # uses IsA<RenderNode> but RenderNode is not an Object
    manual = true
    [[object.function]]
    name = "render_texture"
    # uses IsA<RenderNode> but RenderNode is not an Object
    manual = true

[[object]]
name = "Gsk.Transform"
status = "generate"
    [[object.function]]
    name = "equal"
        [[object.function.parameter]]
            name = "second"
            nullable = false

[[object]]
name = "Gsk.VulkanRenderer"
status = "generate"
cfg_condition = "feature = \"vulkan\""
